update github action add a step to enable action workflows of all submodules.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -67,4 +67,25 @@ jobs:
       uses: ad-m/github-push-action@master
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
+    - name: Enable Action Workflows
+      id: enwf
+      run: |
+        sudo apt install jq -y
+        TOKEN=${{ secrets.GH_PA_TOKEN }}
+        REPOS=($(git config --file .gitmodules --get-regexp url | sed -rn "s#^submodule\.\S+\s+https?://github.com/(.*)(\.git|$)#\1#p"))
+        for repo in ${REPOS[@]}; do
+        workflow_urls=($(curl -H "Authorization: token $TOKEN" \
+                            -H "Accept: application/vnd.github.v3+json" \
+                            https://api.github.com/repos/${repo}/actions/workflows | \
+                            jq ".workflows[] | {url}" | grep -Po '^\s*"url":\s*"\K[^"]+'))
+        echo "Enable action workflows of ${repo} ..."
+        for wf_url in ${workflow_urls[@]}; do
+        printf "[id=${wf_url##*/}]"
+        curl --silent --show-error --fail \
+            -X PUT \
+            -H "Authorization: token $TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            ${wf_url}/enable && echo "Done" || echo "Failed"
+        done
+        done
     
